### ISSUE TITLE
Container fails to start

### ISSUE THREAD

**Issue by finalbillybong** [mylesagray/boilerjuice-tank-api#27]
I've had this running for months but recently noticed that my tank readings were not being reported to Home Assistant. 

I restarted the container and now it fails to start.

```
Traceback (most recent call last):


  File "/app/app.py", line 4, in <module>


    from flask import Response, Flask


  File "/usr/local/lib/python3.10/site-packages/flask/__init__.py", line 14, in <module>


    from jinja2 import escape


  File "/usr/local/lib/python3.10/site-packages/jinja2/__init__.py", line 12, in <module>


    from .environment import Environment


  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 25, in <module>


    from .defaults import BLOCK_END_STRING


  File "/usr/local/lib/python3.10/site-packages/jinja2/defaults.py", line 3, in <module>


    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401


  File "/usr/local/lib/python3.10/site-packages/jinja2/filters.py", line 13, in <module>


    from markupsafe import soft_unicode


ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/local/lib/python3.10/site-packages/markupsafe/__init__.py)


Traceback (most recent call last):


  File "/app/app.py", line 4, in <module>


    from flask import Response, Flask


  File "/usr/local/lib/python3.10/site-packages/flask/__init__.py", line 14, in <module>


    from jinja2 import escape


  File "/usr/local/lib/python3.10/site-packages/jinja2/__init__.py", line 12, in <module>


    from .environment import Environment


  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 25, in <module>


    from .defaults import BLOCK_END_STRING


  File "/usr/local/lib/python3.10/site-packages/jinja2/defaults.py", line 3, in <module>


    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401


  File "/usr/local/lib/python3.10/site-packages/jinja2/filters.py", line 13, in <module>


    from markupsafe import soft_unicode


```

I don't kow where to go from here. Any suggestions?

**Comment by finalbillybong** [comment]
Oh excellent. Thanks for the quick fix. I'll spin up a new container now

**Comment by mylesagray** [comment]
@finalbillybong i take it I’m good to close this?

**Comment by finalbillybong** [comment]
> @finalbillybong i take it I’m good to close this?

Yes! Sorry for not reporting back sooner. Thanks for the quick fix.

**Comment by mylesagray** [comment]
No prob!
