### ISSUE TITLE
Container fails to start on Raspiberry Pi 4 OS Lite

### ISSUE THREAD

**Issue by finalbillybong** [mylesagray/boilerjuice-tank-api#36]
`      

Traceback (most recent call last):

  File "/home/appuser/app.py", line 7, in <module>

    from lxml import html

  File "/.venv/lib/python3.10/site-packages/lxml/html/__init__.py", line 53, in <module>

    from .. import etree

ImportError: Error loading shared library libxslt.so.1: No such file or directory (needed by /.venv/lib/python3.10/site-packages/lxml/etree.cpython-310-arm-linux-gnueabihf.so)

Traceback (most recent call last):

  File "/home/appuser/app.py", line 7, in <module>

    from lxml import html

  File "/.venv/lib/python3.10/site-packages/lxml/html/__init__.py", line 53, in <module>

    from .. import etree

ImportError: Error loading shared library libxslt.so.1: No such file or directory (needed by /.venv/lib/python3.10/site-packages/lxml/etree.cpython-310-arm-linux-gnueabihf.so)

Traceback (most recent call last):

  File "/home/appuser/app.py", line 7, in <module>

    from lxml import html

  File "/.venv/lib/python3.10/site-packages/lxml/html/__init__.py", line 53, in <module>

    from .. import etree

ImportError: Error loading shared library libxslt.so.1: No such file or directory (needed by /.venv/lib/python3.10/site-packages/lxml/etree.cpython-310-arm-linux-gnueabihf.so)

Traceback (most recent call last):

  File "/home/appuser/app.py", line 7, in <module>

    from lxml import html

  File "/.venv/lib/python3.10/site-packages/lxml/html/__init__.py", line 53, in <module>

    from .. import etree

ImportError: Error loading shared library libxslt.so.1: No such file or directory (needed by /.venv/lib/python3.10/site-packages/lxml/etree.cpython-310-arm-linux-gnueabihf.so)`

Container is running fine on Ubuntu Server 18.04 but fails to start on Raspberry Pi OS Lite.

**Comment by mylesagray** [comment]
Are you running it with the Docker container? If not I'd do that to rule out dependency issues.

**Comment by finalbillybong** [comment]
Sorry I'm a little naive and don't know what you mean. I have installed docker and then run the command to install this.... Is that what you mean?

**Comment by finalbillybong** [comment]
I've just tested the hello-world container on Docker and it was fine.

**Comment by mylesagray** [comment]
@finalbillybong no problem! Check out the `Run` section of the readme for an example:

`docker run -d -p 8080:8080 -e BJ_USERNAME=my@emailaddress.com -e BJ_PASSWORD=password -e TANK_ID=yourtankid ghcr.io/mylesagray/boilerjuice-tank`
