### ISSUE TITLE
Container returns error when client asks for update.

### ISSUE THREAD

**Issue by finalbillybong** [mylesagray/boilerjuice-tank-api#50]
`
[2023-03-01 15:14:25,925] ERROR in app: Exception on / [GET]

Traceback (most recent call last):

  File "/.venv/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app

    response = self.full_dispatch_request()

  File "/.venv/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request

    rv = self.handle_user_exception(e)

  File "/.venv/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request

    rv = self.dispatch_request()

  File "/.venv/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request

    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)

  File "/home/appuser/app.py", line 129, in main

    data = {"litres": bj_data["level"], "percent": bj_data["percent"],

KeyError: 'level'

192.168.0.6 - - [01/Mar/2023 15:14:25] "GET / HTTP/1.1" 500 -

[2023-03-01 15:14:42,171] ERROR in app: Exception on / [GET]

Traceback (most recent call last):

  File "/.venv/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app

    response = self.full_dispatch_request()

  File "/.venv/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request

    rv = self.handle_user_exception(e)

  File "/.venv/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request

    rv = self.dispatch_request()

  File "/.venv/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request

    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)

  File "/home/appuser/app.py", line 129, in main

    data = {"litres": bj_data["level"], "percent": bj_data["percent"],

KeyError: 'level'

192.168.0.238 - - [01/Mar/2023 15:14:42] "GET / HTTP/1.1" 500 -

[2023-03-01 15:14:55,041] ERROR in app: Exception on /metrics [GET]

Traceback (most recent call last):

  File "/.venv/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app

    response = self.full_dispatch_request()

  File "/.venv/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request

    rv = self.handle_user_exception(e)

  File "/.venv/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request

    rv = self.dispatch_request()

  File "/.venv/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request

    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)

  File "/home/appuser/app.py", line 147, in metrics

    bj_data = main()

  File "/home/appuser/app.py", line 129, in main

    data = {"litres": bj_data["level"], "percent": bj_data["percent"],

KeyError: 'level'

192.168.0.6 - - [01/Mar/2023 15:14:55] "GET /metrics HTTP/1.1" 500 -

`

**Comment by gr4z** [comment]
Same issue here

**Comment by mylesagray** [comment]
Haven’t had time to look at it, but gut instinct, it sounds like another API/site structure change.

Because we’re scraping their HTML, it’s extremely fragile.

**Comment by finalbillybong** [comment]
Yep looking at the site it has had a total redesign.

**Comment by mylesagray** [comment]
Fixed in b4bd216 - container built.

**Comment by finalbillybong** [comment]
Thank you @mylesagray w=

Its working again.
